FROM node:24.3-bookworm-slim AS build

COPY ./frontend frontend
WORKDIR frontend
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /frontend/dist /usr/share/nginx/html
COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
