apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-resources-all-actions-default
rules:
- apiGroups: ["", "batch", "apps", "rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-resources-all-actions-default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: all-resources-all-actions-default
  apiGroup: "rbac.authorization.k8s.io"
