apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-frontend
  labels:
    app: application-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-frontend
  template:
    metadata:
      labels:
        app: application-frontend
    spec:
      containers:
      - name: cmd-a-frontend
        image: mtrivedi50/cmd-a-frontend
        ports:
          - containerPort: 5173

        env:
          - name: VITE_BACKEND_BASE_URL
            value: http://localhost:8000/
          - name: VITE_ENVIRONMENT
            value: dev

---

apiVersion: v1
kind: Service
metadata:
  name: application-frontend-service
spec:
  selector:
    app: application-frontend
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
  type: ClusterIP
