apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:latest
        ports:
        - containerPort: 7474
        - containerPort: 7687
        env:
        - name: NEO4J_AUTH
          value: neo4j/password
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"

        volumeMounts:
        - name: neo4j-volume-mount

          mountPath: /var/lib/neo4j/data

      volumes:
        - name: neo4j-volume-mount
          persistentVolumeClaim:
            claimName: neo4j-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  selector:
    app: neo4j
  ports:
  - name: http
    protocol: TCP
    port: 7474
    targetPort: 7474
  - name: bolt
    protocol: TCP
    port: 7687
    targetPort: 7687
